trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  minor: 0
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

steps:
- checkout: self
  persistCredentials: true
- script: |
    git config --global user.email "harsha13december@gmail.com"
    git config --global user.name "Harsha"
    npm version patch -m "Bumped version to %s [skip ci]"
    git checkout -b release-$(Build.BuildNumber)
    echo $(major).$(minor).$(patch) > package.json
    git add package.json
    git commit -m "Bump version to $(major).$(minor).$(patch)"
    git push origin release-$(Build.BuildNumber)
