trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  minor: 0
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

steps:
  - name: Configure Git credentials
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      git config --global user.email "harsha13december@gmail.com"
      git config --global user.name "Harsha"

  - script: |
      git checkout -b release-$(Build.BuildNumber)
      echo $(major).$(minor).$(patch) > VERSION
      git add VERSION
      git commit -m "Bump version to $(major).$(minor).$(patch)"
      git push origin release-$(Build.BuildNumber)
    displayName: 'Create release branch and bump version'
