trigger:
- main
vatiables:
major: 1
minor: 0
patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

pool:
  vmImage: ubuntu-latest



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
    - script:  |
         git checkout -b release-$(Build.BuildNumber)
         echo $(major).$(minor).$(patch) > VERSION
         git add VERSION
         git commit -m "Bump version to $(major).$(minor).$(patch)"
         git push origin release-$(Build.BuildNumber)
      displayName: 'Create release branch and bump version'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop